spring:
  application:
    name: eureka-server3
  boot:
    admin:
      context-path: /admin
server:
  port: 8068
eureka:
  instance:
    hostname: eurekaserver3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 
        - http://eurekaserver:8070/eureka/ # connect to eurekaserver
        - http://eurekaserver2:8069/eureka/ # connect to eurekaserver2
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
