spring:
  application:
    name: eureka-server3
  boot:
    admin:
      context-path: /admin
server:
  port: 8068
eureka:
  instance:
    hostname: eurekaserver3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: [http://eurekaserver2:8069/eureka/, http://eurekaserver:8070/eureka/]
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
