spring:
  application:
    name: eureka-server2
  boot:
    admin:
      context-path: /admin
server:
  port: 8069
eureka:
  instance:
    hostname: eurekaserver2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 
        - http://eurekaserver:8070/eureka/ # connect to eurekaserver
        - http://eurekaserver3:8068/eureka/ # connect to eurekaserver3
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
