spring:
  application:
    name: eureka-server2
  boot:
    admin:
      context-path: /admin
server:
  port: 8069
eureka:
  instance:
    hostname: eurekaserver2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: [http://eurekaserver:8070/eureka/, http://eurekaserver3:8068/eureka/]
  server:
    waitTimeInMsWhenSyncEmpty: 5
    enableSelfPreservation: true
    peerNodeConnectTimeoutMs: 10000 # Example: 10 seconds
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
